GET http://localhost:3000

###

GET http://localhost:3000/all-users

###

POST http://localhost:3000/create-user
Content-Type: application/json

{
    "email": "teste@example.com",
    "password": "123456"
}